### ISSUE TITLE
Course searching issues

### ISSUE THREAD

**Issue by churichard** [TigerPathApp/tigerpath#17]
- Fix the extra white space that appears after a long course search
- Need to protect the api endpoints somehow (right now anyone can access them, which is a problem)
- Add a django-admin command to combine semester data from past four years into one comprehensive course list (with typical times that the course is offered, typical semester, etc.)
- When you add a duplicate course, the tooltip shows "Note: class already added" twice
- Sort by the course listing that is most relevant to what the user typed in (e.g. if the user types in "NEU" it should sort by the NEU course listing from lowest code to highest code - I think right now it just sorts alphabetically)

**Comment by danielleung27** [comment]
Fixed, just made a pull request.

**Comment by churichard** [comment]
#18 fixes some of these issues.

Issues that still need to be addressed:

API:
- Need to protect the api endpoints somehow (right now anyone can access them, which is a problem)

Courses data:
- Scrape courses from past 4 semesters (for now) and store in database
- Add a django-admin command to combine semester data from multiple semesters into one comprehensive course list (with typical times that the course is offered, typical semester, etc.)

Frontend:
- Sort by the course listing that is most relevant to what the user typed in (e.g. if the user types in "NEU" it should sort by the NEU course listing from lowest code to highest code. I think right now it just sorts alphabetically, which means that typing in "NEU" gives you EEB403/NEU403 as the top result. NEU200 as the top result makes more sense)
- Add ability to search by course title

Backend:
- Store user schedule in the database (you can modify the user profile model)

**Comment by danielleung27** [comment]
Update: fixed all issues below in new pull request (except the sorting thing)

For the course searching, I think you can search by course title already. Something might not have shown up because only Spring '18 courses are searchable? For the sorting thing, I think princeton courses and recal have the same schema where the listed courses are sorted alphabetically which is why EEB shows up before NEU. One thing I will fix soon so our search mirrors recal is that the ordering of the cross-listings are off right now. For example, a course is listed "TRA301/COS401/LIN304" on recal but on ours it is listed COS401/LIN304/TRA301. It is actually listed "TRA301/COS401/LIN304" on the course registrar because TRA301 is the primary listing and the rest of the cross-listings are in alphabetical order. I think the django model has a field for primary listing so it should be easy to fix.

Actually there's a bug in the course searching filter which might've messed up the title searching. If you want to find the course "Materials Science and Engineering" and you search "materials sci", it treats the 2nd query as a course department and it filters out the list to 0 since a department "sci" doesnt exist. Recal actually does this too. I'll just have a set of departments and check if the query is in it, otherwise it will search for course number then search for title.

**Comment by churichard** [comment]
#20 addresses most of the issues above.

Issues that still need to be addressed:

- Add a django-admin command to combine semester data from multiple semesters into one comprehensive course list (with typical times that the course is offered, typical semester, etc.)
- Sort by the course listing that is most relevant to what the user typed in (e.g. if the user types in "NEU" it should sort by the NEU course listing from lowest code to highest code. I think right now it just sorts alphabetically, which means that typing in "NEU" gives you EEB403/NEU403 as the top result. NEU200 as the top result makes more sense)
- Speed up course searching
- Should be able to search for multiple departments (i.e. "COS ELE" should search for crosslisted courses in COS and ELE)
